name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # or main, depending on your default branch name

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --configuration production --base-href="https://mohamedsallam1234.github.io/ecommerce-final/" --aot --output-hashing=all

      - name: Copy index.html to 404.html
        run: cp www/index.html www/404.html

      - name: Add .nojekyll file
        run: touch www/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
          branch: gh-pages
          clean: true
